# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numdias', models.DecimalField(decimal_places=0, max_digits=2)),
                ('valord', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechain', models.DateTimeField(auto_now_add=True)),
                ('fechafin', models.DateTimeField()),
                ('estado', models.CharField(max_length=10)),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('idTrabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajadores')),
            ],
        ),
    ]
