# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fechafin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
