# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20160603_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='valord',
            new_name='valordiario',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='fechain',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='fechainicio',
            field=models.DateField(default=datetime.datetime(2016, 6, 3, 17, 19, 8, 189000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fechafin',
            field=models.DateField(),
        ),
    ]
