# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('idTrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('cedulatr', models.CharField(max_length=20)),
                ('nombretr', models.CharField(max_length=50)),
                ('apellstr', models.CharField(max_length=80)),
                ('teltr', models.CharField(max_length=20)),
                ('direcciontr', models.CharField(max_length=30)),
                ('tipoacc', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
