# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apells', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
    ]
